# Header
menu:
  ## If your site is put in a subdirectory, set Home as '/child/'
  Home: /
  Archives: archives

social:
  email:
  twitter: sujunmin_
  weibo:
  github: sujunmin
  googleplus: +JunMingSu
  rss: /atom.xml

# Content
fancybox: true # set to true if you want to use it

duoshuo: #duoshuo_shortname
disqus: sujunmin

google_analytics: UA-78894509-1
google_adsense_page_level_ads: ca-pub-0187888667607442
valine:
  enable: false
